### ISSUE TITLE
Error:(44, 25) TS2339: Property 'iCheck' does not exist on type 'JQuery'.

### ISSUE THREAD

**Issue by tobiashoeft** [hasanhameed07/angular2-dashboard-starter#2]
Error:(44, 25) TS2339: Property 'iCheck' does not exist on type 'JQuery'.****

Hey I receive this message?

**Comment by jdobbin-hsahealthplan** [comment]
I got that message too, It doesn't seem to be an issue when actually loading the app.

**Comment by JoshDobbin** [comment]
Try this `typings install icheck --ambient --save`
