### ISSUE TITLE
Property 'iCheck' does not exist on type 'JQuery'.

### ISSUE THREAD

**Issue by zuoez02** [hasanhameed07/angular2-dashboard-starter#6]
I cloned the project and npm install, then I use npm start , but failed.

src/app/auth_module/signup/signup.component.ts(44,25): error TS2339: Property 'iCheck' does not exist on type 'JQuery'.

Why?

**Comment by esneivro** [comment]
There is one closed issue (#2) regarding this problem. Anyway I think the project works without solve it...
